content/config.yml

Add Kit's OSS contributions.

---

templates/base.html

To deal with our spamalytics problems.

Add spam-referrals-blocker JS library

---

STYLEGUIDE.md

PT story: https://www.pivotaltracker.com/story/show/139869601

Content rules include dashes and line length

---

.gitignore
content/config-dev.yml
gulpfile.js
package.json
static/js/spamReferralsBlocker.js
templates/base.html
webpack.common.config.js
yarn.lock

https://www.pivotaltracker.com/story/show/139567121

Update GA spam-referrals on "gulp prod"; filter out local traffic.

---

modules/jinja_macros.py

Pass config into render context

---

modules/jinja_macros.py

Handle encoding shenanigans

---

content/2017/02/20/color-theory-for-coders.rst
content/docs/grid-template.rst
content/docs/sample.rst
static/sass/components/_post-header.scss
static/sass/config/_scale.scss
templates/blog/index.html
templates/layout/macros.j2

PT Story: https://www.pivotaltracker.com/story/show/141882215
I think we will probably want to think of types to document in the content guidelines. Conversation can take place in PT.

Post titles

---

static/sass/patterns/_tags.scss

no PT story, something I noticed in the last week or so and had a minute to fix.

tags lack of hover was driving me crazy

---

content/birds/index.rst
content/community.rst
content/contact/index.rst
content/contact/thanks.rst
content/index.rst
content/speaking.rst
content/work/index.rst
templates/layout/macros.j2

Based on https://www.pivotaltracker.com/n/projects/22378/stories/138947673

Page titles and descriptions

---

static/sass/components/_author.scss
static/sass/config/_scale.scss
static/sass/patterns/_inverted.scss
static/sass/patterns/_sections.scss
templates/rst_display.html

Fix for author box.
PT: https://www.pivotaltracker.com/story/show/145884429

[author-fix] make sure global pseudo margin doesn’t apply to author row

---

content/index.rst
static/sass/patterns/_alignment.scss
templates/birds/macros.j2

hopefully addressing the concern that we look like a team of three - by moving the team image higher on the page.

Rearrange the home page

---

content/2017/03/20/serializing-things.rst

Add reader feedback to Serializing Things for Celery

---

content/susy/sites.rst

I left the screenshot for now, but removed links.

Remove links to Virgin America.

---

content/talks/advanced-css-workshop.rst
content/talks/advanced-python.rst
content/talks/agile-systems-workshop.rst
content/talks/agile-systems.rst
content/talks/automated-testing.rst
content/talks/code-patterns.rst
content/talks/code-reviews.rst
content/talks/curing-complacency.rst
content/talks/data-design.rst
content/talks/greater-than-the-sum.rst
content/talks/inside-pip-virtualenv.rst
content/talks/losing-control.rst
content/talks/no-grid-system.rst
content/talks/practical-layouts.rst
content/talks/python-testing-tools.rst
content/talks/sass-map-magic.rst
content/talks/sass-partials.rst
content/talks/sassy-toolkits.rst
content/talks/set-your-code-free.rst
content/talks/software-for-humans.rst
content/talks/state-of-design.rst
content/talks/susy-system.rst
content/talks/taming-dependencies-pip.rst
content/talks/tbd.rst
content/talks/testing-django.rst
content/talks/theme-building.rst
content/talks/web-project.rst
templates/community/events.macros.j2
templates/layout/macros.j2

@jgerigmeyer @SondraE I updated my speaking schedule, and split talks/workshops on the speaking page because the combined list was getting long. Nothing much needed here: just check for typos, and make sure I didn't break things?

[talks] Update talks and workshops

---

content/jobs.rst

[no-job] Replace hiring contact with notice

---

pull_request_template.md

*Don't forget to link from Trello to the PR as well*
*The commit messages say what you did, this should explain why and how.*
This PR will hopefully provide additional details for future PRs by providing a standard (maybe overly informative) set of instructions/requests. Basically, sometimes Stacy can't find what she is supposed to test.
*Please provide how to best reproduce the issue and how to test the fix locally*
I think this only works when we merge it into master, then create a new PR
* * *

Hopefully Create Pull Request Template

---

README.rst

*The commit messages say what you did, this should explain why and how.*
No card, only using this branch to test PR template and it is working!
*Please provide how to best reproduce the issue and how to test the fix locally*
You'll see it on your next PR
*Provide screenshots/animated gifs/videos if necessary*

Remove assuming word “just”

---

content/2018/12/12/channels-and-drf.rst

There was a misnamed variable in the example code, which a reader helpfully pointed out. I have corrected the name.

Fix example code

---

content/services/planning.rst

https://trello.com/c/t7PUuPMc/29-i-want-quick-updates-to-research-discovery-page-for-accuracy
*We are currently charging $5K for the list of items on the Planning Page, not $8K.*
*Look at the Research & Concepting page*
*https://www.oddbird.net/services/planning/*
* * *

updated discovery price

---

content/2016/03/01/sass-book.rst
content/2016/10/18/versioning.rst
content/2018/12/04/views-on-vue.rst
content/2019/03/26/thunder-nerds.rst
content/2019/07/02/vov-068.rst
content/podcasts/thunder-nerds.rst
content/podcasts/versioning.rst
content/podcasts/vov-040.rst
content/podcasts/vov-068.rst
content/talks/sass-map-magic.rst
content/talks/software-for-humans.rst
templates/community/events.macros.j2
templates/layout/macros.j2

https://trello.com/c/B2eVTlrI/22-2-i-want-to-post-existing-podcast-videos-and-interviews-for-oddsite-visitors
- Event list links point to posts when available
- Podcast event pages, and linked articles
- New Thunder Nerds & VoV articles

Add versioning show audio, and fix links/posts

---

content/index.rst
static/sass/config/_layout.scss
static/sass/config/_scale.scss
static/sass/patterns/_image-blocks.scss
static/sass/patterns/_manifest.scss
static/sass/patterns/_text-blocks.scss
templates/home.macros.j2

*Don't forget to link from Trello to the PR as well*
https://trello.com/c/Qwruwz9h/2-i-want-a-specific-design-for-the-home-page
*The commit messages say what you did, this should explain why and how.*
Notes: The XD file says to make links semi-bold, but we aren't loading a semibold font file at this time. I am not sure we should unless the links we currently have styled are bothering anyone? Also, same goes for the light weight font. I am calling font-weight: 300 for the `.fancy-headline-light` lines but I probably should change it to normal unless adding the light weight font file is something we want to add. We could probably load just these letters we are using at the time so it won't effect performance too much, do @SondraE or @mirisuzanne have strong feelings about this?
@mirisuzanne …

add expertise/dedicated service block on homepage

---

content/talks/css-is-rad.rst
content/talks/software-for-humans.rst
content/talks/tbd.rst

https://deploy-preview-419--oddsite.netlify.com/
Update talks at…
- Smashing Conf NY
- Agnes Scott College
- `/services/speaking/`
- `/authors/miriam/`
- `/talks/css-is-rad/`

Update SmashingConf NY and add Agnes Scott

---

content/2019/10/01/mozdev.rst
content/2019/10/02/sass-modules.rst
content/mozdev/list-markers.rst

- fixes an rst typo in the list-marker files
- adds a sass-modules primer, since it may be a few days before the CSS Tricks post…

A quick primer, while we wait

---

content/talks/resilient-systems.rst
templates/content.macros.j2
templates/layout/macros.j2

https://deploy-preview-482--oddsite.netlify.com/
on `/talks/resilient-systems/` workshop page…
- changed the image to be more personal
- clean up subtitle & cta-button language
- add a title to the grid of modules 
- change the byline to `with` for speaking pages

Small changes to the workshop page

---

content/services/speaking.rst
content/talks/agile-systems.rst
content/talks/resilient-systems.rst

Because there's been some attention to the workshop, and questions on twitter, I thought I'd clean it up and flesh it out a bit…

Update workshop page

---

content/community/index.rst
content/config.yml

Oh hey I guess it's 2020 now?
